services:
  db:
    image: postgres
    container_name: db_support
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  bot:
    build:
      context: .
    container_name: support_tg_bot
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
