services:
  db:
    image: postgres
    container_name: db
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
  