"""finish_base

Revision ID: 749c19fafdaf
Revises: 
Create Date: 2024-11-26 05:08:55.668724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749c19fafdaf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('EXECUTIVE_DIRECTOR', 'ACCOUNT_MANAGER', 'SENIOR_CLO_MANAGER', 'CLO_MANAGER', name='category'), nullable=False),
    sa.Column('free', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managers_name'), 'managers', ['name'], unique=False)
    op.create_index(op.f('ix_managers_surname'), 'managers', ['surname'], unique=False)
    op.create_index(op.f('ix_managers_user_id'), 'managers', ['user_id'], unique=True)
    op.create_index(op.f('ix_managers_username'), 'managers', ['username'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('request_category', sa.Enum('ORDER', 'PAYMENT', 'ACCOUNT', 'OTHER', name='request_category'), nullable=False),
    sa.Column('subcategory', sa.Enum('RESET_NP_AND_CHANGE_PAYER', 'CREATE_INVOICE_OR_REQUEST', 'CHANGE_RECIPIENT_CONTACTS', 'CHANGE_DELIVERY_MODE_OR_PICKUP', 'ORDER_FORWARDING', 'CARGO_SEARCH', 'CONSULTATION_ON_TS_AND_DELIVERY', 'PROVIDE_DOCUMENTS', 'CUSTOM_SUBCATEGORY', 'NOT_SETUP', name='subcategory'), nullable=False),
    sa.Column('close', sa.Boolean(), nullable=False),
    sa.Column('contact_number_or_inn', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=2500), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('rating_value', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_table('messages')
    op.drop_table('requests')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_managers_username'), table_name='managers')
    op.drop_index(op.f('ix_managers_user_id'), table_name='managers')
    op.drop_index(op.f('ix_managers_surname'), table_name='managers')
    op.drop_index(op.f('ix_managers_name'), table_name='managers')
    op.drop_table('managers')
    # ### end Alembic commands ###
