"""add vacation

Revision ID: 0951e130daf4
Revises: 4539861e234d
Create Date: 2024-12-05 00:04:33.195796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0951e130daf4'
down_revision: Union[str, None] = '4539861e234d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('holiday_start', sa.DateTime(), nullable=True))
    op.add_column('managers', sa.Column('holiday_end', sa.DateTime(), nullable=True))
    op.add_column('managers', sa.Column('number', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managers', 'number')
    op.drop_column('managers', 'holiday_end')
    op.drop_column('managers', 'holiday_start')
    # ### end Alembic commands ###
