"""last_update

Revision ID: d2bebd9f1551
Revises: 0951e130daf4
Create Date: 2024-12-05 19:09:42.957655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2bebd9f1551'
down_revision: Union[str, None] = '0951e130daf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('vacation_start', sa.DateTime(), nullable=True))
    op.add_column('managers', sa.Column('vacation_end', sa.DateTime(), nullable=True))
    op.drop_column('managers', 'holiday_start')
    op.drop_column('managers', 'holiday_end')
    op.add_column('requests', sa.Column('manager_closed', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'manager_closed')
    op.add_column('managers', sa.Column('holiday_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('managers', sa.Column('holiday_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('managers', 'vacation_end')
    op.drop_column('managers', 'vacation_start')
    # ### end Alembic commands ###
